"""Signed regular-origin terms in the dual-weighted response estimator.

This module certifies the two center contributions

``J_rigid+B(y_h)`` and ``R_y(z_h)``

on ``0 <= x <= x0``.  It uses ``t=x^2`` throughout.  The weak master
functional has density ``x^4 H(t)``, while the primal strong residual and
adjoint trial factor as ``r_y=x r_hat(t)`` and ``z_h=x a_z(t)``.  The volume
weights are exactly ``x0^5/5`` and ``x0^3/3``.  Because the neighboring outer
residual is retained in weak form, the origin action also keeps the cutoff
trace ``r1(x0) dot z_h(x0)`` generated by integration by parts.
"""

from __future__ import annotations

from dataclasses import dataclass
from fractions import Fraction
from math import comb

from .centrifugal_skyrmion_rational_response_trials import RationalResponseTrial
from .validated_centrifugal_origin_adjoint_load import (
    ValidatedOriginWeakMasterLoadCell,
    validated_origin_weak_master_load_cell,
)
from .validated_centrifugal_origin_profile_jets import (
    rational_origin_trial_cell_from_archive,
    validated_authenticated_origin_profile_kernel_cells,
)
from .validated_centrifugal_origin_response_residual import (
    RationalOriginTrialCell,
    ValidatedOriginStrongResidual,
    validated_origin_conormal_cell_from_profile,
    validated_origin_strong_residual_cell,
)
from .validated_interval import (
    RationalInterval,
    RationalPolynomial,
    sqrt_fraction_interval,
)
from .validated_skyrmion_quintic_family import ValidatedSkyrmionQuinticFamily


IntervalVector2 = tuple[RationalInterval, RationalInterval]


def _polynomial_linear_combination(
    terms: tuple[tuple[Fraction, RationalPolynomial, int], ...],
) -> RationalPolynomial:
    """Return ``sum scale*tau^shift*p(tau)`` exactly."""
    if not terms:
        return RationalPolynomial((Fraction(0),))
    degree = max(polynomial.degree + shift for _, polynomial, shift in terms)
    coefficients = [Fraction(0) for _ in range(degree + 1)]
    for scale, polynomial, shift in terms:
        if shift < 0:
            raise ValueError("polynomial shift must be nonnegative")
        for index, coefficient in enumerate(polynomial.coefficients):
            coefficients[index + shift] += scale * coefficient
    return RationalPolynomial(tuple(coefficients))


def _bernstein_range_on_unit(polynomial: RationalPolynomial) -> RationalInterval:
    """Enclose a power-basis polynomial by its exact Bernstein hull."""
    degree = polynomial.degree
    if degree == 0:
        return RationalInterval.point(polynomial.coefficients[0])
    bernstein = []
    for index in range(degree + 1):
        coefficient = Fraction(0)
        for power in range(index + 1):
            if power <= polynomial.degree:
                coefficient += polynomial.coefficients[power] * Fraction(
                    comb(index, power), comb(degree, power)
                )
        bernstein.append(coefficient)
    return RationalInterval(min(bernstein), max(bernstein))


@dataclass(frozen=True)
class ValidatedRegularTrialPhysicalRanges:
    """Exact-polynomial ranges of ``a=y/x`` and ``d=y'``."""

    field_over_radius: IntervalVector2
    physical_derivative: IntervalVector2


def validated_regular_trial_physical_ranges(
    trial: RationalOriginTrialCell,
) -> ValidatedRegularTrialPhysicalRanges:
    """Range one exact regular trial after cancellation in normalized time."""
    if not isinstance(trial, RationalOriginTrialCell):
        raise TypeError("trial must be a RationalOriginTrialCell")
    horizon = trial.time_horizon
    u = trial.u
    v = trial.v
    u_tau = u.derivative()
    v_tau = v.derivative()
    radial_over_radius = _polynomial_linear_combination(
        (
            (Fraction(-1), v, 0),
            (horizon, u, 1),
        )
    )
    radial_derivative = _polynomial_linear_combination(
        (
            (Fraction(-1), v, 0),
            (3 * horizon, u, 1),
            (Fraction(-2), v_tau, 1),
            (2 * horizon, u_tau, 2),
        )
    )
    tangential_derivative = _polynomial_linear_combination(
        (
            (Fraction(1), v, 0),
            (Fraction(2), v_tau, 1),
        )
    )
    return ValidatedRegularTrialPhysicalRanges(
        field_over_radius=(
            _bernstein_range_on_unit(radial_over_radius),
            _bernstein_range_on_unit(v),
        ),
        physical_derivative=(
            _bernstein_range_on_unit(radial_derivative),
            _bernstein_range_on_unit(tangential_derivative),
        ),
    )


@dataclass(frozen=True)
class ValidatedOriginMasterFunctionalContribution:
    """Signed center contribution to ``J_rigid+B(y_h)``."""

    density_hat: RationalInterval
    radial_weight: Fraction
    contribution: RationalInterval


def validated_origin_master_functional_contribution(
    load: ValidatedOriginWeakMasterLoadCell,
    primal_trial: RationalOriginTrialCell,
) -> ValidatedOriginMasterFunctionalContribution:
    """Enclose ``integral x^4 H(t) dx`` for one profile cell."""
    if load.time != RationalInterval(0, primal_trial.time_horizon):
        raise ValueError("load and primal trial origin cells differ")
    ranges = validated_regular_trial_physical_ranges(primal_trial)
    density = load.rigid_density_hat
    for coefficient, field in zip(
        load.field_over_radius_coefficient,
        ranges.field_over_radius,
        strict=True,
    ):
        density += coefficient * field
    for coefficient, field in zip(
        load.physical_derivative_coefficient,
        ranges.physical_derivative,
        strict=True,
    ):
        density += coefficient * field
    root = sqrt_fraction_interval(primal_trial.time_horizon).lower
    if root * root != primal_trial.time_horizon:
        raise ValueError("time horizon must be a rational square")
    weight = root**5 / 5
    return ValidatedOriginMasterFunctionalContribution(
        density_hat=density,
        radial_weight=weight,
        contribution=density.scale(weight),
    )


@dataclass(frozen=True)
class ValidatedOriginPrimalResidualAction:
    """Signed center action ``R_y(z_h)``."""

    action_density_hat: RationalInterval
    radial_weight: Fraction
    volume_action: RationalInterval
    cutoff_test_value: IntervalVector2
    cutoff_trace: RationalInterval
    action: RationalInterval


def validated_origin_primal_residual_action(
    primal_residual: ValidatedOriginStrongResidual,
    adjoint_trial: RationalOriginTrialCell,
) -> ValidatedOriginPrimalResidualAction:
    """Enclose the strong origin volume and its weak cutoff trace.

    With weak residual coefficients ``r0,r1`` and
    ``r=r0-r1'``, integration by parts on ``[0,x0]`` gives

    ``R_y(z_h)=integral r dot z_h dx+r1(x0) dot z_h(x0)``.

    The center trace vanishes by regularity.  The cutoff term must remain when
    the neighboring positive-radius residual is evaluated in weak form.
    """
    if primal_residual.time != RationalInterval(0, adjoint_trial.time_horizon):
        raise ValueError("primal residual and adjoint trial origin cells differ")
    adjoint = validated_regular_trial_physical_ranges(adjoint_trial)
    density = RationalInterval.point(0)
    for residual, field in zip(
        primal_residual.residual_hat,
        adjoint.field_over_radius,
        strict=True,
    ):
        density += residual * field
    weight = primal_residual.radius_cutoff**3 / 3
    volume = density.scale(weight)
    endpoint_value, _ = adjoint_trial.physical_endpoint_jet()
    cutoff_test_value = tuple(RationalInterval.point(entry) for entry in endpoint_value)
    cutoff_trace = sum(
        (
            residual * field
            for residual, field in zip(
                primal_residual.cutoff_derivative_residual,
                cutoff_test_value,
                strict=True,
            )
        ),
        RationalInterval.point(0),
    )
    return ValidatedOriginPrimalResidualAction(
        action_density_hat=density,
        radial_weight=weight,
        volume_action=volume,
        cutoff_test_value=cutoff_test_value,  # type: ignore[arg-type]
        cutoff_trace=cutoff_trace,
        action=volume + cutoff_trace,
    )


@dataclass(frozen=True)
class ValidatedOriginCorrectedEstimatorCell:
    """Both signed estimator terms on one authenticated slope cell."""

    shooting_slopes: RationalInterval
    master_functional: ValidatedOriginMasterFunctionalContribution
    primal_residual: ValidatedOriginStrongResidual
    residual_action: ValidatedOriginPrimalResidualAction
    corrected_contribution: RationalInterval


@dataclass(frozen=True)
class ValidatedOriginCorrectedEstimatorFamily:
    """Signed origin estimator enclosure over the full slope family."""

    primal_trial_name: str
    adjoint_trial_name: str
    cells: tuple[ValidatedOriginCorrectedEstimatorCell, ...]
    master_functional_hull: RationalInterval
    residual_volume_action_hull: RationalInterval
    residual_cutoff_trace_hull: RationalInterval
    residual_action_hull: RationalInterval
    corrected_contribution_hull: RationalInterval


def _hull(values: tuple[RationalInterval, ...]) -> RationalInterval:
    if not values:
        raise ValueError("at least one interval is required")
    return RationalInterval(
        min(value.lower for value in values),
        max(value.upper for value in values),
    )


def validated_archived_origin_corrected_estimator_family(
    family: ValidatedSkyrmionQuinticFamily,
    primal_trial: RationalResponseTrial,
    adjoint_trial: RationalResponseTrial,
    *,
    kernel_terms: int = 12,
    green_terms: int = 12,
    gravitational_coupling: Fraction = Fraction(1),
) -> ValidatedOriginCorrectedEstimatorFamily:
    """Certify both signed origin terms over every profile-family cell."""
    if not isinstance(family, ValidatedSkyrmionQuinticFamily):
        raise TypeError("family must be a ValidatedSkyrmionQuinticFamily")
    for name, trial in (("primal", primal_trial), ("adjoint", adjoint_trial)):
        if not isinstance(trial, RationalResponseTrial):
            raise TypeError(f"{name}_trial must be a RationalResponseTrial")
        trial.validate()
        if trial.origin.cutoff != family.cutoff:
            raise ValueError(f"{name} trial and profile-family cutoffs differ")
    primal = rational_origin_trial_cell_from_archive(primal_trial.origin)
    adjoint = rational_origin_trial_cell_from_archive(adjoint_trial.origin)
    profiles = validated_authenticated_origin_profile_kernel_cells(
        family,
        kernel_terms=kernel_terms,
    )
    cells = []
    for authenticated in profiles:
        profile = authenticated.kernels
        load = validated_origin_weak_master_load_cell(
            profile,
            curvature=family.curvature,
            pion_mass_squared=family.pion_mass_squared,
            gravitational_coupling=gravitational_coupling,
            patch_radius=Fraction(20),
            green_terms=green_terms,
        )
        master = validated_origin_master_functional_contribution(load, primal)
        coefficients = validated_origin_conormal_cell_from_profile(
            profile,
            pion_mass_squared=family.pion_mass_squared,
        )
        residual = validated_origin_strong_residual_cell(coefficients, primal)
        action = validated_origin_primal_residual_action(residual, adjoint)
        cells.append(
            ValidatedOriginCorrectedEstimatorCell(
                shooting_slopes=authenticated.shooting_slopes,
                master_functional=master,
                primal_residual=residual,
                residual_action=action,
                corrected_contribution=master.contribution + action.action,
            )
        )
    result = tuple(cells)
    return ValidatedOriginCorrectedEstimatorFamily(
        primal_trial_name=primal_trial.name,
        adjoint_trial_name=adjoint_trial.name,
        cells=result,
        master_functional_hull=_hull(
            tuple(cell.master_functional.contribution for cell in result)
        ),
        residual_volume_action_hull=_hull(
            tuple(cell.residual_action.volume_action for cell in result)
        ),
        residual_cutoff_trace_hull=_hull(
            tuple(cell.residual_action.cutoff_trace for cell in result)
        ),
        residual_action_hull=_hull(
            tuple(cell.residual_action.action for cell in result)
        ),
        corrected_contribution_hull=_hull(
            tuple(cell.corrected_contribution for cell in result)
        ),
    )
